### ISSUE TITLE
Add all the team

### ISSUE THREAD

**Issue by MrGKanev** [IEEE-Student-Branch-of-Uni-Ruse/website#4]
We have a team page with a small part of the team there. It would be awesome if we have everyone added to it.

**Comment by seabeePraveen** [comment]
I am intrested in doing it!...can i do this?

**Comment by MrGKanev** [comment]
Yep, why not. Could you try to make the team part into a component for easier management in the future? Here are the names of the rest of the team:

* Teodor Nenov
* Plamena Dinolova
* Todor Yordanov
* Reni Kabakchieva
* Atanas Kabakchiev
* Metin Ibryamov
* Tsvetelina Stefanova 
* Aleksandar Ivanov 
* Dimitar Dimitrov
* Emil Stefanov
* Atila Pandzhar
* Martin Nedelchev
* Martin Minchev
* Denis Sami
* Preslav Stoyanov
* Deyan Dzhumaliyski
* Konstantin T

When you are ready, you can make a PR and put me on it. :) If there are any questions, ask. :)

**Comment by seabeePraveen** [comment]
yeah okay i'll let you know

**Comment by atilapan** [comment]
The component part still needs to be made, I have hardcoded the rest of the team.
